=== Loweise/liga-mx-dtld-xml/dtd/resultados.dtd
<!ELEMENT partido (equipo+)>
<!ELEMENT equipo (goles, posesion, tarjetas)>
<!ELEMENT goles (#PCDATA)>
<!ELEMENT posesion (#PCDATA)>
<!ELEMENT tarjetas (#PCDATA)>
<!ATTLIST partido id ID #REQUIRED>
<!ATTLIST equipo 
    estadia (local|visitante) #IMPLIED
    nombre CDATA #REQUIRED>

=== Loweise/liga-mx-dtld-xml/xml/resultados-invalido.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partido SYSTEM "../dtd/resultados.dtd">
<partido id="p12"> 

    <equipo estadia="local" nombre="Monterrey">
        <goles>1</goles>
        <posesion>50</posesion>
        <tarjetas>0</tarjetas>
    </equipo>

    <equipo estadia="local" >
        <posesion>50</posesion>
        <goles>0</goles>
        <tarjetas>1</tarjetas> 
        <indicepapeo> </indicepapeo>
    </equipo>

</partido>
<partido id="p12"></partido>
